### ISSUE TITLE
Ensure consistent grouping of future map plate layer into eras

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#129]
Right now, there's some inconsistency of the future eras that the map plates are showing.  Many plates show 2040-2069 but some are showing 2090-2099 or 2070-2099.  This can be because of the way that the data are batched during ingest (or the nature of the dataset), but it could be good to survey and make this more consistent where possible.

**Comment by brucecrevensten** [comment]
First step here is to list the future groupings/eras for all plates, then we can look at that and decide what makes sense.

**Comment by cstephen** [comment]
Here's an inventory of the eras from each plate, excluding the Ecoregions and Geology plates because they don't have eras.

## Climate

### Precipitation:
- 1980-2009: computed via WCPS query
- 2040-2069: computed via WCPS query

### Snowfall
- 1910-1919: precomputed by decade
- 2090-2099: precomputed by decade

### Temperature
- 1980-2009: computed via WCPS query
- 2040-2069: computed via WCPS query

## Engineering

### Design Freezing Index
- 1980-2009: precomputed by era
- 2070-2099: precomputed by era

### Design Thawing Index:
- 1980-2009: precomputed by era
- 2070-2099: precomputed by era

### Freezing Index:
- 1980-2009: computed via WCPS query
- 2040-2069: computed via WCPS query

### Thawing Index:
- 1980-2009: computed via WCPS query
- 2040-2069: computed via WCPS query

### Heating Degree Days:
- 1980-2009: computed via WCPS query
- 2040-2069: computed via WCPS query

## Physiography

### Permafrost:
- 1986-2005: precomputed by era
- 2036-2065: precomputed by era
- 2000-2016: precomputed by era

Excluding the Permafrost plate, which has its own era system, it looks we can use WCPS queries to standardize all of the other plates into the following eras without re-postprocessing & re-ingesting:

- 1980-2009
- 2070-2099

For the coverages that have already been pre-computed into decades, we can simply average them across 3 decades.

**Comment by brucecrevensten** [comment]
I think like we could improve this but honestly I think we're close to about as good as it gets here.  Most plates are self-consistent unless the data are bundled differently at a lower level -- since these are just "glances," I'm good with closing this ticket!
