### ISSUE TITLE
Consider tweaking Snowfall color map to distribute colors better

### ISSUE THREAD

**Issue by cstephen** [ua-snap/arctic-eds#177]
For example, we may want to switch to using a linear color map instead of an exponential one, similar to what we did for the Engineering plates, to help distribute the colors more evenly across the map.

**Comment by brucecrevensten** [comment]
Next step here is to check in with Nancy + Charlie for what they'd expect to see for this.

**Comment by charparr** [comment]
We changed the model / scenario of the slice being requested, and that seemed to help! I don't think we touched the underlying blurple colormap. @cstephen if you are satisfied then you can close this issue, otherwise leave a suggestion! Snowfall Equivalent is a tough one for color mapping because you have zero in some places and terabuckets of snow in the mountains and glaciers.

**Comment by brucecrevensten** [comment]
I'm good with it, closing!
