### ISSUE TITLE
Heating DD and Freezing Index Units Not Converting

### ISSUE THREAD

**Issue by charparr** [ua-snap/arctic-eds#385]
When I toggle from Imperial to Metric, the summary tables for HDD and Freezing index retain the Imperial values and units.
However, thawing index (in the same section) seems to be functioning as expected.

STR:
Load a report (try JBER)
Observe HDD and FI values in default Imperial units
Toggle to Metric
Observe that the HDD and FI values still use F-days and the units have not changed

**Comment by brucecrevensten** [comment]
I think the issue here is basically that the wrong unit label was shown for Thawing Index.  It should be ºF•days.  I think it's OK to not convert these as part of an immediate fix, because these units are sort of pinned to F.  (I am almost sure we can offer the conversion but from my [limited] reading it seems like ºF•days may be a near-universal convention for our audience).
