### ISSUE TITLE
Provide our definition of degree days, freezing index, thawing index.

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#388]
There are some definitions which may be more specific or incompatible with how we're defining these terms.

Should we specify what we're doing, exactly?

**Comment by charparr** [comment]
We should! This is a good idea, and something I spoke to John Zarling about a while ago. Eventually we may want to add other methods. Here is the synopsis of my conversation with him.

We are basically doing a "cumulative" method vs. a "seasonal" method.

For example for freezing index, we are summing the number of degree-days below 0 degrees Celsius, calculated as the arithmetic sum of all the negative mean daily air temperatures (degrees Celsius). In practice, this is pretty simple with the WRF dataset:
```python
threshold = 32
`freezing_index = threshold - ((ds.t2.values - 273.15) * 9/5 + 32`
```

However, there is a **seasonal** method that is perhaps more commonly used. It goes like this: 

Start calculating degree days on January 1st of some year. For an example Interior AK location, that computation will obviously yield a negative number. Do this every day and compute a cumulative, running sum. Over winter and into spring, you'd expect that you have a number that is increasingly negative. In spring you may oscillate between freezing and thawing, so the number grows larger and smaller, but eventually the cumulative sum will reach **some minimum value**. As spring becomes summer, the numbers are positive until say Oct. 1, and then in fall there is a freeze/thaw mix, but eventually the cumulative sum will reach **some maximum value**, and then in winter the daily numbers are all negative again.

To compute the seasonal thawing index, subtract the minimum at the end of winter from the maximum at the end of summer.

To compute the seasonal freezing index, subtract the maximum at the end of summer from the minimum that occurs at the end of the following spring.

This is a little more complicated because you need to identify the min-max on the cumulative degree-day time curve, but probably not beyond us.

We're also still **only** using WRF 20 km data because that was all we had at the time, but now that we have other daily data (NCAR 12 km) at our disposal that we are using in production for beetles, hydrology, and indicators, it'd make sense to provide another flavor of degree day output and move away from the coarser WRF data that we know is fraught with biases. 

This would be a very good update for a version 1.x of the EDS.

**Comment by charparr** [comment]
First sentence of data intro specifies we use the cumulative method.
